# SPDX-License-Identifier: MIT
"""Secret and credential regex pattern libraries."""

CUSTOM_SECRET_PATTERNS: dict[str, str] = {
    "AWS Access Key ID": r"AKIA[0-9A-Z]{16}",
    "AWS Secret Access Key": r"(?i)aws(.{0,20})?['\"][0-9a-zA-Z/+]{40}['\"]",
    "Google API Key": r"AIza[0-9A-Za-z\-_]{35}",
    "GitHub Token": r"(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36,255}",
    "Generic API Key": r"(?i)(api[_-]?key|apikey|secret).{0,10}['\"]([a-zA-Z0-9_\-]{16,64})['\"]",
    "Private Key Header": r"-----BEGIN (RSA |EC |DSA )?PRIVATE KEY-----",
    "JWT Token": r"eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}",
    "Slack Token": r"xox[baprs]-[A-Za-z0-9\-_]+",
    "Stripe Key": r"(sk|rk)_(live|test)_[A-Za-z0-9]+",
    "Generic Password Assignment": r"(?i)(password|passwd|pwd)\s*[:=]\s*['\"]([^'\"]+)['\"]",
    "Vercel Token": r"vercel_[A-Za-z0-9]{24,}",
    "Supabase Token": r"sbp_[a-zA-Z0-9]{40}",
    "Cloudflare API Key": r"[a-zA-Z0-9_\-]{40}",
    "Snowflake Password": r"(?i)snowflake.*password.*['\"][^'\"]+['\"]",
    "Datadog API Key": r"(?i)datadog.*['\"][a-f0-9]{32}['\"]",
    "Docker Password/Token": r"(?i)ENV\s+\w*(?:PASSWORD|PASS|SECRET|KEY|TOKEN|AUTH)\w*\s*=\s*['\"].*?['\"]",
    "Kubernetes Config Secret": r"(?i)(?:client-certificate-data\s*:\s*[A-Za-z0-9+/]{40,}=*|client-key-data\s*:\s*[A-Za-z0-9+/]{40,}=*)",
    "Terraform Hardcoded Credential": r"(?i)(?:aws_access_key|aws_secret_key|token|password|secret|api_key)\s*=\s*['\"].*?['\"]",
    "DYNA_TRACE_API_TOKEN": r"dt0c01\.[a-zA-Z0-9]{24,}(?:\.[a-zA-Z0-9]{24,})*",
    "DYNA_TRACE_ENV_ID": r"(?i)dynatrace.*?(?:environmentid|envid|tenant)\s*[:=]\s*['\"][a-zA-Z0-9\-]{8,}['\"]",
    "DYNA_TRACE_CONFIG": r"(?i)(dynatrace|oneagent).*?(token|apikey|password)",
    "POWER_QUERY_WEBCONTENTS": r"(?i)Web\.Contents\s*\(\s*\"[^\"]*\"",
    "POWER_QUERY_CONNECTION_STRING": r"(?i)(?:Server|Database|User|Password)\s*=\s*\"[^\"]+\"",
    "POWER_QUERY_HARDCODED_KEY": r"(?i)(?:api[_-]?key|token|secret)\s*=\s*\"[^\"]{8,}\"",
    "POWER_QUERY_EXTENSION_CREDENTIAL": r"(?i)Extension\.CurrentCredential\s*\(\s*\)",
    "SCALA_CONFIG_SECRET": r"(?i)(?:password|secret|key|token)\s*=\s*\"[^\"]{6,}\"",
    "HASKELL_CONFIG_SECRET": r"(?i)(?:password|apikey|accessKey)\s*=\s*\"[^\"]{6,}\"",
    "ELIXIR_SYSTEM_FETCH": r"(?i)System\.fetch_env!\s*\(\s*\"[A-Z_]+\"\s*\)",
    "CLOJURE_SYSTEM_GETENV": r"(?i)System/getenv\s+\"[^\"]+\"",
    "CASE_CLASS_SECRET": r"(?i)(?:case\s+class|data\s+class)\s+\w+\([^)]*?(?:password|secret|key|token)\s*:\s*\"[^\"]+\"",
}

GITROB_CONTENT_PATTERNS: dict[str, str] = {
    "AWS API Key": r"AKIA[0-9A-Z]{16}",
    "AWS Secret Key": r"[0-9a-zA-Z/+]{40}",
    "Google Cloud Platform API Key": r"AIza[0-9A-Za-z\-_]{35}",
    "GitHub OAuth Access Token": r"gho_[0-9a-zA-Z]{36,255}",
    "Heroku API Key": r"[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}",
    "Slack Webhook": r"https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}",
    "Twilio API Key": r"SK[0-9a-fA-F]{32}",
    "Twilio Auth Token": r"[a-zA-Z0-9]{32}",
    "Mailgun API Key": r"key-[0-9a-zA-Z]{32}",
    "Mailchimp API Key": r"[0-9a-f]{32}-us[0-9]{1,2}",
    "SendGrid API Key": r"SG\.[\w_-]{22,68}\.[\w_-]{22,68}",
    "Square Access Token": r"sq0atp-[0-9A-Za-z\-_]{22}",
    "Square OAuth Secret": r"sq0csp-[0-9A-Za-z\-_]{43}",
    "PayPal/Braintree Access Token": r"access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}",
    "Picatic API Key": r"sk_live_[0-9a-z]{32}",
    "Facebook Access Token": r"EAACEdEose0cBA[0-9A-Za-z]+",
    "Twitter Access Token": r"[tT][wW][iI][tT][tT][eE][rR].*[1-9][0-9]+-[0-9a-zA-Z]{40}",
    "Twitter OAuth Secret": r"[a-zA-Z0-9]{35,44}",
    "LinkedIn Client ID": r"^[0-9A-Za-z]{14,16}$",
    "Connection String": r"(?i)(?:mongodb|mysql|postgresql|redis|sqlite)://[^ \n]+",
    "Bearer Token": r"(?i)bearer\s+[a-zA-Z0-9\-\._~\+\/]+=*",
}

GITROB_SUSPICIOUS_FILES: list[str] = [
    "id_rsa",
    "id_dsa",
    "id_ed25519",
    "id_ecdsa",
    "*.pem",
    "*.key",
    "*.pkcs12",
    "*.pfx",
    "*.p12",
    "*.crt",
    "*.cert",
    "*.ca-bundle",
    "*.jks",
    "*.keystore",
    "*.keytab",
    "credentials*",
    "secrets*",
    "secret*",
    ".env",
    ".env.*",
    "*.env",
    "config.yml",
    "config.yaml",
    "config.json",
    "config.xml",
    "config.properties",
    "*.config",
    ".git-credentials",
    ".s3cfg",
    ".tugboat",
    "proftpdpasswd",
    ".htpasswd",
    ".netrc",
    "wp-config.php",
    "database.yml",
    "settings.py",
    ".bash_history",
    ".mysql_history",
    ".psql_history",
    ".pgpass",
    "shadow",
    "passwd",
    "mcp.json",
    "dynatrace.config.yaml",
    "dynatrace.config.yml",
    "dtconfig.json",
    "oneagent-install.sh",
    "*.dynatrace",
    ".dynatrace/",
    "*.pq",
    "*.m",
    "*.mashup",
    "*.query",
    "*.odc",
    "*.pbix",
]
